type Intent =
	| "GUILDS"
	| "GUILD_MEMBERS"
	| "GUILD_BANS"
	| "GUILD_EMOJIS"
	| "GUILD_INTEGRATIONS"
	| "GUILD_WEBHOOKS"
	| "GUILD_INVITES"
	| "GUILD_VOICE_STATES"
	| "GUILD_PRESENCES"
	| "GUILD_MESSAGES"
	| "GUILD_MESSAGE_REACTIONS"
	| "GUILD_MESSAGE_TYPING"
	| "DIRECT_MESSAGES"
	| "DIRECT_MESSAGE_REACTIONS"
	| "DIRECT_MESSAGE_TYPING";

class Intents {
	bits: number;

	static intentsMap = {
		GUILDS: 0,
		GUILD_MEMBERS: 1,
		GUILD_BANS: 2,
		GUILD_EMOJIS: 3,
		GUILD_INTEGRATIONS: 4,
		GUILD_WEBHOOKS: 5,
		GUILD_INVITES: 6,
		GUILD_VOICE_STATES: 7,
		GUILD_PRESENCES: 8,
		GUILD_MESSAGES: 9,
		GUILD_MESSAGE_REACTIONS: 10,
		GUILD_MESSAGE_TYPING: 11,
		DIRECT_MESSAGES: 12,
		DIRECT_MESSAGE_REACTIONS: 13,
		DIRECT_MESSAGE_TYPING: 14
	};

	static ALL: Intent[] = [
		"GUILDS",
		"GUILD_MEMBERS",
		"GUILD_BANS",
		"GUILD_EMOJIS",
		"GUILD_INTEGRATIONS",
		"GUILD_WEBHOOKS",
		"GUILD_INVITES",
		"GUILD_VOICE_STATES",
		"GUILD_PRESENCES",
		"GUILD_MESSAGES",
		"GUILD_MESSAGE_REACTIONS",
		"GUILD_MESSAGE_TYPING",
		"DIRECT_MESSAGES",
		"DIRECT_MESSAGE_REACTIONS",
		"DIRECT_MESSAGE_TYPING"
	];

	static NON_PRIVILEGED: Intent[] = [
		"GUILDS",
		"GUILD_MEMBERS",
		"GUILD_BANS",
		"GUILD_EMOJIS",
		"GUILD_INTEGRATIONS",
		"GUILD_WEBHOOKS",
		"GUILD_INVITES",
		"GUILD_VOICE_STATES",
		"GUILD_MESSAGES",
		"GUILD_MESSAGE_REACTIONS",
		"GUILD_MESSAGE_TYPING",
		"DIRECT_MESSAGE_REACTIONS",
		"DIRECT_MESSAGE_TYPING"
	];

	static PRIVILEGED: Intent[] = ["GUILD_PRESENCES", "GUILD_MEMBERS"];

	constructor(intents: Intent[] = Intents.NON_PRIVILEGED) {
		let bits = 1;
		for (const intent of intents) {
			bits << Intents.intentsMap[intent];
		}
		this.bits = bits;
	}
}

export default Intents;
